##########################################################################
#                                                                        #
#                          Service Identity Part                         #
#               For Further information, please check README             #
#                                                                        #
##########################################################################

service:
  name: "micoboParty"
  id: 1 
  baseURL: "/v1/"
  http:
    host: "0.0.0.0"
    port: "8080"
    requestTimeout: 32

##########################################################################
#                                                                        #
#                         Server Config Part                             #
#       Please set the server parameters based on your own settings      #
#                                                                        #
##########################################################################


postgres:
  username: "admin"
  password: "password"
  host: "postgres"
  port: "5432"
  db: "micobo"
  sslmode: "disable"
  timezone: "Europe/Berlin"
