version: "3.7"

services:
  micobo:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/go/src/application
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_USER)
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: unless-stopped
